### ISSUE TITLE
How to install and use on latest umbrel via docker

### ISSUE THREAD

**Issue by TylonHH** [rkfg/regolancer#64]
I tried both commands. No ones work

```
umbrel@umbrel:~$ docker build -t regolancer .
[+] Building 0.2s (1/1) FINISHED                docker:default
 => [internal] load build definition from Dockerfile      0.1s
 => => transferring dockerfile: 2B                        0.0s
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

umbrel@umbrel:~$ docker pull ziggie1984/regolancer
Using default tag: latest
Error response from daemon: manifest for ziggie1984/regolancer:latest not found: manifest unknown: manifest unknown

```

**Comment by rkfg** [comment]
The second command would try downloading an image from https://hub.docker.com/r/ziggie1984/regolancer/tags — see the available tags, they're pretty much outdated and there's no `latest` tag so you need to specify it explicitly. As for the first command, I just tried it and it works. You need to clone the repo first and run `docker build -t regolancer .` inside.

**Comment by TylonHH** [comment]
Oh I see.
Would you mind updating the readme? Especially the docker section?! 

I stuck here now after `go install github.com/rkfg/regolancer@latest `

```
umbrel@umbrel:~/go/bin$ ls
regolancer
umbrel@umbrel:~/go/bin$ docker build -t regolancer .
[+] Building 0.1s (1/1) FINISHED                docker:default
 => [internal] load build definition from Dockerfile      0.0s
 => => transferring dockerfile: 2B                        0.0s
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
```

Edit
```umbrel@umbrel:~$ sudo docker pull rkfg/regolancer
Using default tag: latest
Error response from daemon: pull access denied for rkfg/regolancer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied ```

**Comment by TylonHH** [comment]
ok , I somehow managed to install it. I also set alias, copied the config to `config.json`, set the cache path.

So next step as I guess is to run it with `-f`?

```
umbrel@umbrel:~$ ls /home/umbrel/regolancer/
cache.go      channels.go  config.json.sample  Dockerfile  go.mod         go.sum     helpmessage  LICENSE  mission_ctl.go  payment.go  rebalancer.go  screenshot.png
CHANGELOG.md  config.json  config.toml.sample  format.go   goreleaser.md  helper.go  info.go      main.go  node_cache      README.md   routes.go      version.go
umbrel@umbrel:~$ regolancer -f /home/umbrel/regolancer/config.json
2025/01/16 06:29:10 Error opening config file /home/umbrel/regolancer/config.json: open /home/umbrel/regolancer/config.json: no such file or directory

````

**Comment by rkfg** [comment]
You need to have the config inside the container, either put it into a volume or mount just that file with `-v`. Containers don't "see" your main file system, they have their own.

>I stuck here now after go install github.com/rkfg/regolancer@latest 

You don't need to do that if you use Docker. You also should run the docker build command in the cloned repo directory, not ~/go/bin

**Comment by TylonHH** [comment]
`~/go/bin/regolancer -f /home/umbrel/regolancer/config.toml`
works now.

here is my conf if you mind take a look. I have currently 28 channels with total cap of 6.2M so in generall 200k each channel.
Most of the attempts failure...

<details><summary>--info</summary>
<p>

```
——————————————————————————————————————————————————————————————————————————————————————————————————
From 9 channels                                   To 12 channels
——————————————————————————————————————————————————————————————————————————————————————————————————
retiringon.bitcoin [myNod [|||||||||      ] 65%    ThorLightning             [||||           ] 30%
1ML.com node ALPHA        [|||||||||||||| ] 99%    Lightning.Store           [|||            ] 23%
1ML.com node ALPHA        [|||||||||||||| ] 99%    DarthPikachu              [||||           ] 28%
CoinGate                  [|||||||||||||| ] 97%    UmbrelReach               [||||           ] 30%
Alex71btc ⚡🚀            [|||||||||||||| ] 97%    kappa                     [||             ] 14%
coincharge                [|||||||||||||  ] 93%    Babylon-4a                [||             ] 17%
034b4658f3e6c3114c64      [|||||||||||||| ] 99%    ***ROUTE 66***            [|              ] 7%
Kiminofreedom             [|||||||||||||  ] 93%    LNBϟG [Hub-1]             [|||            ] 22%
schulzemic [LND]          [|||||||||      ] 62%    nicehash-ln1              [               ] 4%
                                                   BrokenThunder⚡           [               ] 6%
                                                   deZentraliZe              [||             ] 16%
                                                   Clack Bank                [|||            ] 24%
——————————————————————————————————————————————————————————————————————————————————————————————————
Min amount: 5,000 sat
Amount: 20,000 sat
Max fee: 120% of target channel ppm
Fail tolerance: 1,000 ppm
Rapid rebalance: disabled
Lost profit accounting: enabled
Probing steps: 15
Node cache size: 312 records, life time: 1 days 0 hours 0 minutes
Show node cache hits: disabled
Total rebalance timeout: 6 hours 0 minutes
Single attempt timeout: 5 minutes
Info query timeout: 30 seconds
Route query timeout: 30 seconds
```


</p>
</details> 
<details><summary>config.toml</summary>
<p>

```toml
"macaroon_dir" = "/home/umbrel/umbrel/app-data/lightning/data/lnd/data/chain/bitcoin/mainnet/"
"macaroon_filename" = "admin.macaroon"
"network" = "mainnet"
"tlscert" = "/home/umbrel/umbrel/app-data/lightning/data/lnd/tls.cert"
"perc" = 40
# "pto" = 1
# "pfrom" = 30
"econ_ratio" = 1.0
"econ-ratio-max-ppm" = 1500
"amount" = 20000
"min_amount" = 5000
"rel-amount-from" = 0.45
"rel-amount-to" = 0.5
"probe_steps" = 15
"allow-rapid-rebalance" = true
# "pfrom" = 80
# "pto" = 1
"lost_profit" = true
"timeout_rebalance" = 360
"timeout_attempt" = 5
"timeout_info" = 30
"timeout_route" = 30
"node_cache_filename" = "/home/umbrel/regolancer/node_cache/cache.dat"
"node-cache-lifetime" = 720
"node-cache-info" = true
"stat" = "/home/umbrel/regolancer/node_cache/stats.csv"
# "info" = true
"info" = false
```
</p>
</details> 

also, after setting amount to 100k
```
Probing route...
2025/01/16 11:36:52 5000 requires too high fee 7 (max allowed is 4), increasing amount to 52500
2025/01/16 11:37:02 52500 is too much, lowering amount to 28750, 14 steps left
2025/01/16 11:37:10 28750 is too much, lowering amount to 16875, 13 steps left
2025/01/16 11:37:10 16875 requires too high fee 17 (max allowed is 16), increasing amount to 22812
2025/01/16 11:37:16 22812 is too much, lowering amount to 19844, 12 steps left
2025/01/16 11:37:16 19844 requires too high fee 19 (max allowed is 19), increasing amount to 21328
2025/01/16 11:37:22 21328 is too much, lowering amount to 20586, 11 steps left
2025/01/16 11:37:22 20586 requires too high fee 19 (max allowed is 19), increasing amount to 20957
2025/01/16 11:37:22 20957 requires too high fee 20 (max allowed is 20), increasing amount to 21142
2025/01/16 11:38:15 21142 is too much, lowering amount to 21050, 10 steps left
2025/01/16 11:38:23 21050 is too much, lowering amount to 21004, 9 steps left
2025/01/16 11:38:23 21004 requires too high fee 20 (max allowed is 20), increasing amount to 21027
2025/01/16 11:38:23 21027 requires too high fee 20 (max allowed is 20), increasing amount to 21038
2025/01/16 11:38:23 Best amount is unknown
```
schould I increase the econ rate?

**Comment by rkfg** [comment]
Most attempts are expected to fail because cheap liquidity is quickly sniped by the similar tools. If you increase the econ rate above 1.0 you'd agree to rebalance at a loss possibly, up to you if it's worth it. 15 probing steps are not worth it, if you just slightly missed the available balance it's usually estimated well enough within 5 steps. I don't rebalance now myself and instead apply dynamic fee rate and max HTLC policies.

**Comment by TylonHH** [comment]
OK got it. Thanks for fast response.
I  works now with fix amount like `-a 100000`

But how do I use `--rel-amount-from` to be more flexible of the amount?

My understanding this conf should work. I tried many possibilities to exclude arguments but I always get
`no amount specified, use either --amount, --rel-amount-from, or --rel-amount-to`

<details><summary>Details</summary>
<p>

```toml
"macaroon_dir" = "/home/umbrel/umbrel/app-data/lightning/data/lnd/data/chain/bitcoin/mainnet/"
"macaroon_filename" = "admin.macaroon"
"network" = "mainnet"
"tlscert" = "/home/umbrel/umbrel/app-data/lightning/data/lnd/tls.cert"
#"perc" = 30
"econ_ratio" = 0.8
"econ-ratio-max-ppm" = 1500
# "amount" = 100000
# "min_amount" = 5000
"rel-amount-from" = 0.4
#"rel-amount-to" = 0.5
"probe_steps" = 5
"allow-rapid-rebalance" = true
"pfrom" = 30
"pto" = 30
"lost_profit" = true
"timeout_rebalance" = 360
"timeout_attempt" = 5
"timeout_info" = 30
"timeout_route" = 30
"node_cache_filename" = "/home/umbrel/regolancer/node_cache/cache.dat"
"node-cache-lifetime" = 720
"node-cache-info" = true
"stat" = "/home/umbrel/regolancer/node_cache/stats.csv"
#"info" = true
"info" = false
````

</p>
</details>
